### ISSUE TITLE
Indentation issue in code

### ISSUE THREAD

**Issue by hayesla** [lkilcommons/geospacepy-lite#1]
Line 50, 51 of lmk_utils.py has an extra space before tab which is an issue. A simple fix but just thought I would flag it.

'''In [1]: from geospacepy import omnireader
Traceback (most recent call last):

  File "/opt/anaconda36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-7275736bb430>", line 1, in <module>
    from geospacepy import omnireader

  File "/opt/anaconda36/lib/python3.6/site-packages/geospacepy-0.1.0-py3.6.egg/geospacepy/omnireader.py", line 3, in <module>
    from geospacepy import special_datetime

  File "/opt/anaconda36/lib/python3.6/site-packages/geospacepy-0.1.0-py3.6.egg/geospacepy/special_datetime.py", line 16, in <module>
    from geospacepy import lmk_utils #my toolbox of convenience functions

  File "/opt/anaconda36/lib/python3.6/site-packages/geospacepy-0.1.0-py3.6.egg/geospacepy/lmk_utils.py", line 50
    arr.fill(numpy.nan)
                       ^
TabError: inconsistent use of tabs and spaces in indentation'''

**Comment by lkilcommons** [comment]
Thanks for taking the time Laura, I'll take care of it.
BTW lmk_utils is one my oldest modules, and I tend not to even import it in most of the newer geospacepy modules. I wrote a lot of those convenience functions before I knew that there are usually one-liners in numpy for most of the same functionality. Let me know if you find anything else!

**Comment by imnotkk** [comment]
Hey I'm facing the same issue too. Any leads?

**Comment by imnotkk** [comment]
Btw I found a temporary workaround by commenting the while nan() funtion which gave me the Indentation error in lmk_utils.py .

Hope this would be checked and solved in the future.

**Comment by hayesla** [comment]
Yes, if you go into the lmk_utils.py and take away the space on line 50 and 51 it works

**Comment by lkilcommons** [comment]
Fixed. It would help me if you could let me know what Python version you are using. Possibly there are other indentation issues. We develop on 2.7 so if you are using 3.x it would be good to know.

**Comment by hayesla** [comment]
Great, using Python 3.6, and haven't had any other issues!
