### ISSUE TITLE
omnireader won't connect to OMNI ftp server unless FTP -> FTP_TLS

### ISSUE THREAD

**Issue by Dartspacephysiker** [lkilcommons/geospacepy-lite#4]
In the file omnireader.py, I had to change the line

```
            ftp = ftplib.FTP(self.ftpserv)
```
to 
```
            ftp = ftplib.FTP_TLS(self.ftpserv)
```
to be able to download OMNI data. I believe the OMNI servers were just updated to require a secure connection.

**Comment by rmcgranaghan** [comment]
This is correct, here is the relevant note from SPDF along with some potential fixes: https://spdf.gsfc.nasa.gov/ftps_readme.html

**Comment by lkilcommons** [comment]
I accepted a pull request about 10 days ago fixing this. Is it still not working?

**Comment by rmcgranaghan** [comment]
My apologies - had not updated the package. It works for me now. Thanks!

**Comment by lkilcommons** [comment]
No worries, and thank you both for reporting the issue to me! That's what makes this open source thing work.
